<#
.SYNOPSIS
  Inventory local Pickle suites, including Git-ignored standalone repositories.
.DESCRIPTION
  Run from any directory. -Check reads only and fails on missing suite notes or a stale snapshot.
  Requires rg. Does not follow directory links, inspect Git history, compile, or launch a game.
  Counts source attribute declarations, not resolved Cucumber expressions or runtime coverage.
#>
param(
    [string]$CollectionRoot = (Split-Path (Split-Path $PSScriptRoot -Parent) -Parent),
    [switch]$Check
)
$ErrorActionPreference = 'Stop'
$root = (Resolve-Path -LiteralPath $CollectionRoot).Path
$scanArgs = @('--files', '--hidden', '--no-ignore',
    '-g', '*.cs', '-g', '*.feature',
    '-g', '!**/.git/**', '-g', '!**/obj/**', '-g', '!**/bin/**', '-g', '!**/.build/**',
    '-g', '!_mods-sources/**', '-g', '!reference/**', '-g', '!PickleTools/**')
$files = @(& rg @scanArgs $root)
if ($LASTEXITCODE -ne 0) { throw 'rg could not inventory the collection' }
$suites = @{}
foreach ($file in $files) {
    $relative = $file.Substring($root.Length + 1).Replace('\', '/')
    if ($relative -notmatch '^(?<owner>.+)/tests/pickle/(?<part>Source/.+\.cs|Mod/Pickle/Features/.+\.feature)$') { continue }
    $owner = $Matches.owner
    $part = $Matches.part
    if (-not $suites.ContainsKey($owner)) {
        $suites[$owner] = @{ Sources = @(); Features = 0; Steps = 0 }
    }
    if ($part -like '*.feature') { $suites[$owner].Features++; continue }
    $source = [IO.File]::ReadAllText($file)
    $count = [regex]::Matches($source, '(?m)^\s*\[(?:Given|When|Then|Step)\s*\(').Count
    $suites[$owner].Sources += [pscustomobject]@{ Path = $relative; Count = $count }
    $suites[$owner].Steps += $count
}
if ($suites.Count -eq 0) { throw 'No suites found; check CollectionRoot' }
$lines = [Collections.Generic.List[string]]::new()
$lines.Add('# Local suite inventory')
$lines.Add('')
$lines.Add('Generated by `Update-Inventory.ps1`; edit the suite notes, then regenerate this snapshot.')
$lines.Add('')
$lines.Add('Scope: current local `Tests/Pickle/Source/*.cs` (recursive) and `Mod/Pickle/Features/*.feature`, case-insensitive, including ignored repositories. Directory links are not followed, so the FlavorText aliases are counted only at their real paths. PickleTools itself, build output and imported source/reference corpora are excluded. External checkouts and deleted historical steps are not exhaustively searched.')
$lines.Add('')
$lines.Add('Declarations are line-leading Given/When/Then/Step attributes counted from source text; they are not resolved expressions, unique patterns, executed steps or a collision check. Helper files with zero declarations remain listed. Features are files shipped by the suite, not scenarios or reports. Runtime evidence stays in the dated suite notes.')
$lines.Add('')
$lines.Add('| Suite | Source files | Step declarations | Feature files | Notes |')
$lines.Add('|---|---:|---:|---:|---|')
$missing = @()
foreach ($owner in ($suites.Keys | Sort-Object)) {
    $suite = $suites[$owner]
    $leaf = ($owner -split '/')[-1]
    $note = "$leaf.md"
    if (-not (Test-Path -LiteralPath (Join-Path $PSScriptRoot $note))) { $missing += $owner }
    $lines.Add(('| `{0}` | {1} | {2} | {3} | [{4}]({4}) |' -f $owner, $suite.Sources.Count, $suite.Steps, $suite.Features, $note))
}
$lines.Add('')
$lines.Add('## Source files')
foreach ($owner in ($suites.Keys | Sort-Object)) {
    $lines.Add('')
    $lines.Add("### $owner")
    $lines.Add('')
    if ($suites[$owner].Sources.Count -eq 0) {
        $lines.Add('No local C# source found in this suite. See its note for shared tools or historical code.')
    } else {
        foreach ($src in ($suites[$owner].Sources | Sort-Object Path)) {
            $lines.Add(('- `{0}`: {1} step declarations.' -f $src.Path, $src.Count))
        }
    }
}
if ($missing.Count) { throw ('Missing suite notes: ' + ($missing -join ', ')) }
$expected = ($lines -join "`n") + "`n"
$target = Join-Path $PSScriptRoot 'INVENTORY.md'
if ($Check) {
    if (-not (Test-Path -LiteralPath $target)) { throw 'INVENTORY.md is missing' }
    $actual = [IO.File]::ReadAllText($target).Replace("`r`n", "`n")
    if ($actual -cne $expected) { throw 'INVENTORY.md is stale; run Update-Inventory.ps1 without -Check' }
    Write-Output "Inventory matches local sources; $($suites.Count) suites have notes. No runtime validation performed."
} else {
    [IO.File]::WriteAllText($target, $expected, [Text.UTF8Encoding]::new($false))
    Write-Output "Wrote $target ($($suites.Count) suites)."
}
