# Finishes the south of the river of the Sanctuaire de Nelim (Virginie, 2026-10-04): it runs to the bottom edge of the map as the UPSTREAM,
# so it narrows, bends and gains shoals from z 60 down to z 0, with a gravel bank, and keeps flowing off the map. Bamboo grew over the water of rows 61-72 and over all of the south: it is cleared. The rows from z 60 up are not touched:
# row z 60 is laid exactly as the save has it (centre x 114, shallow x 109-119, deep x 111-117). The result is saved as "nelims-tribe-river".
# Generated by the scratch script of the session that wrote it (a sine centre line and a width that grows with z); the cells are the contract.
#
#   scripts/Run-PickleWsl.ps1 -Mod PickleTools -DepMap wsl-deps.sanctuary.map -Filter pickletools-sanctuary-river
@requires:nelim.pickletools.stagedecor
@requires:nelim.pickletools.camerazoom
Feature: Sanctuaire river, upstream end

  Background:
    Given the save "Nelims-tribe" is loaded
    And game speed is paused

  Scenario: the river narrows and bends towards the bottom edge
    Given Nelim's Pickle Tools: the area from (100, 61) to (128, 72) is cleared
    And Nelim's Pickle Tools: the area from (108, 0) to (120, 0) is cleared
    And Nelim's Pickle Tools: I lay the floor "MossyTerrain" from (104, 0) to (124, 0)
    And Nelim's Pickle Tools: I lay the floor "Gravel" from (110, 0) to (118, 0)
    And Nelim's Pickle Tools: I lay the floor "WaterShallow" from (111, 0) to (117, 0)
    And Nelim's Pickle Tools: I lay the floor "WaterDeep" from (113, 0) to (115, 0)
    And Nelim's Pickle Tools: the area from (110, 1) to (122, 1) is cleared
    And Nelim's Pickle Tools: I lay the floor "MossyTerrain" from (104, 1) to (124, 1)
    And Nelim's Pickle Tools: I lay the floor "Gravel" from (112, 1) to (120, 1)
    And Nelim's Pickle Tools: I lay the floor "WaterShallow" from (113, 1) to (119, 1)
    And Nelim's Pickle Tools: I lay the floor "WaterDeep" from (115, 1) to (117, 1)
    And I spawn a "Plant_Reeds" at (113, 1)
    And I spawn a "Plant_Reeds" at (119, 1)
    And Nelim's Pickle Tools: the area from (111, 2) to (123, 2) is cleared
    And Nelim's Pickle Tools: I lay the floor "MossyTerrain" from (104, 2) to (124, 2)
    And Nelim's Pickle Tools: I lay the floor "Gravel" from (113, 2) to (121, 2)
    And Nelim's Pickle Tools: I lay the floor "WaterShallow" from (114, 2) to (120, 2)
    And Nelim's Pickle Tools: I lay the floor "WaterDeep" from (116, 2) to (118, 2)
    And Nelim's Pickle Tools: the area from (113, 3) to (123, 3) is cleared
    And Nelim's Pickle Tools: I lay the floor "MossyTerrain" from (104, 3) to (124, 3)
    And Nelim's Pickle Tools: I lay the floor "Gravel" from (115, 3) to (121, 3)
    And Nelim's Pickle Tools: I lay the floor "WaterShallow" from (116, 3) to (120, 3)
    And Nelim's Pickle Tools: I lay the floor "WaterDeep" from (117, 3) to (119, 3)
    And Nelim's Pickle Tools: the area from (113, 4) to (123, 4) is cleared
    And Nelim's Pickle Tools: I lay the floor "MossyTerrain" from (104, 4) to (124, 4)
    And Nelim's Pickle Tools: I lay the floor "Gravel" from (115, 4) to (121, 4)
    And Nelim's Pickle Tools: I lay the floor "WaterShallow" from (116, 4) to (120, 4)
    And Nelim's Pickle Tools: I lay the floor "WaterDeep" from (117, 4) to (119, 4)
    And Nelim's Pickle Tools: the area from (113, 5) to (123, 5) is cleared
    And Nelim's Pickle Tools: I lay the floor "MossyTerrain" from (104, 5) to (124, 5)
    And Nelim's Pickle Tools: I lay the floor "Gravel" from (115, 5) to (121, 5)
    And Nelim's Pickle Tools: I lay the floor "WaterShallow" from (116, 5) to (120, 5)
    And Nelim's Pickle Tools: I lay the floor "WaterDeep" from (117, 5) to (119, 5)
    And I spawn a "Plant_Reeds" at (116, 5)
    And I spawn a "Plant_Reeds" at (120, 5)
    And Nelim's Pickle Tools: the area from (113, 6) to (123, 6) is cleared
    And Nelim's Pickle Tools: I lay the floor "MossyTerrain" from (104, 6) to (124, 6)
    And Nelim's Pickle Tools: I lay the floor "Gravel" from (115, 6) to (121, 6)
    And Nelim's Pickle Tools: I lay the floor "WaterShallow" from (116, 6) to (120, 6)
    And Nelim's Pickle Tools: I lay the floor "WaterDeep" from (117, 6) to (119, 6)
    And Nelim's Pickle Tools: the area from (112, 7) to (122, 7) is cleared
    And Nelim's Pickle Tools: I lay the floor "MossyTerrain" from (104, 7) to (124, 7)
    And Nelim's Pickle Tools: I lay the floor "Gravel" from (114, 7) to (120, 7)
    And Nelim's Pickle Tools: I lay the floor "WaterShallow" from (115, 7) to (119, 7)
    And Nelim's Pickle Tools: I lay the floor "WaterDeep" from (116, 7) to (118, 7)
    And Nelim's Pickle Tools: the area from (111, 8) to (121, 8) is cleared
    And Nelim's Pickle Tools: I lay the floor "MossyTerrain" from (104, 8) to (124, 8)
    And Nelim's Pickle Tools: I lay the floor "Gravel" from (113, 8) to (119, 8)
    And Nelim's Pickle Tools: I lay the floor "WaterShallow" from (114, 8) to (118, 8)
    And Nelim's Pickle Tools: I lay the floor "WaterDeep" from (115, 8) to (117, 8)
    And Nelim's Pickle Tools: the area from (111, 9) to (121, 9) is cleared
    And Nelim's Pickle Tools: I lay the floor "MossyTerrain" from (104, 9) to (124, 9)
    And Nelim's Pickle Tools: I lay the floor "Gravel" from (113, 9) to (119, 9)
    And Nelim's Pickle Tools: I lay the floor "WaterShallow" from (114, 9) to (118, 9)
    And Nelim's Pickle Tools: I lay the floor "WaterDeep" from (115, 9) to (117, 9)
    And I spawn a "Plant_Reeds" at (114, 9)
    And I spawn a "Plant_Reeds" at (118, 9)
    And Nelim's Pickle Tools: the area from (110, 10) to (120, 10) is cleared
    And Nelim's Pickle Tools: I lay the floor "MossyTerrain" from (104, 10) to (124, 10)
    And Nelim's Pickle Tools: I lay the floor "Gravel" from (112, 10) to (118, 10)
    And Nelim's Pickle Tools: I lay the floor "WaterShallow" from (113, 10) to (117, 10)
    And Nelim's Pickle Tools: I lay the floor "WaterDeep" from (114, 10) to (116, 10)
    And Nelim's Pickle Tools: the area from (109, 11) to (121, 11) is cleared
    And Nelim's Pickle Tools: I lay the floor "MossyTerrain" from (104, 11) to (124, 11)
    And Nelim's Pickle Tools: I lay the floor "Gravel" from (111, 11) to (119, 11)
    And Nelim's Pickle Tools: I lay the floor "WaterShallow" from (112, 11) to (118, 11)
    And Nelim's Pickle Tools: I lay the floor "WaterDeep" from (114, 11) to (116, 11)
    And Nelim's Pickle Tools: the area from (109, 12) to (121, 12) is cleared
    And Nelim's Pickle Tools: I lay the floor "MossyTerrain" from (104, 12) to (124, 12)
    And Nelim's Pickle Tools: I lay the floor "Gravel" from (111, 12) to (119, 12)
    And Nelim's Pickle Tools: I lay the floor "WaterShallow" from (112, 12) to (118, 12)
    And Nelim's Pickle Tools: I lay the floor "WaterDeep" from (114, 12) to (116, 12)
    And Nelim's Pickle Tools: the area from (109, 13) to (121, 13) is cleared
    And Nelim's Pickle Tools: I lay the floor "MossyTerrain" from (104, 13) to (124, 13)
    And Nelim's Pickle Tools: I lay the floor "Gravel" from (111, 13) to (119, 13)
    And Nelim's Pickle Tools: I lay the floor "WaterShallow" from (112, 13) to (118, 13)
    And Nelim's Pickle Tools: I lay the floor "WaterDeep" from (114, 13) to (116, 13)
    And I spawn a "Plant_Reeds" at (112, 13)
    And I spawn a "Plant_Reeds" at (118, 13)
    And Nelim's Pickle Tools: the area from (110, 14) to (120, 14) is cleared
    And Nelim's Pickle Tools: I lay the floor "MossyTerrain" from (104, 14) to (124, 14)
    And Nelim's Pickle Tools: I lay the floor "Gravel" from (112, 14) to (118, 14)
    And Nelim's Pickle Tools: I lay the floor "WaterShallow" from (113, 14) to (117, 14)
    And Nelim's Pickle Tools: I lay the floor "WaterDeep" from (114, 14) to (116, 14)
    And Nelim's Pickle Tools: the area from (109, 15) to (121, 15) is cleared
    And Nelim's Pickle Tools: I lay the floor "MossyTerrain" from (104, 15) to (124, 15)
    And Nelim's Pickle Tools: I lay the floor "Gravel" from (111, 15) to (119, 15)
    And Nelim's Pickle Tools: I lay the floor "WaterShallow" from (112, 15) to (118, 15)
    And Nelim's Pickle Tools: I lay the floor "WaterDeep" from (113, 15) to (117, 15)
    And Nelim's Pickle Tools: the area from (109, 16) to (121, 16) is cleared
    And Nelim's Pickle Tools: I lay the floor "MossyTerrain" from (104, 16) to (124, 16)
    And Nelim's Pickle Tools: I lay the floor "Gravel" from (111, 16) to (119, 16)
    And Nelim's Pickle Tools: I lay the floor "WaterShallow" from (112, 16) to (118, 16)
    And Nelim's Pickle Tools: I lay the floor "WaterDeep" from (113, 16) to (117, 16)
    And Nelim's Pickle Tools: the area from (109, 17) to (121, 17) is cleared
    And Nelim's Pickle Tools: I lay the floor "MossyTerrain" from (104, 17) to (124, 17)
    And Nelim's Pickle Tools: I lay the floor "Gravel" from (111, 17) to (119, 17)
    And Nelim's Pickle Tools: I lay the floor "WaterShallow" from (112, 17) to (118, 17)
    And Nelim's Pickle Tools: I lay the floor "WaterDeep" from (114, 17) to (116, 17)
    And I spawn a "Plant_Reeds" at (112, 17)
    And I spawn a "Plant_Reeds" at (118, 17)
    And Nelim's Pickle Tools: the area from (108, 18) to (120, 18) is cleared
    And Nelim's Pickle Tools: I lay the floor "MossyTerrain" from (104, 18) to (124, 18)
    And Nelim's Pickle Tools: I lay the floor "Gravel" from (110, 18) to (118, 18)
    And Nelim's Pickle Tools: I lay the floor "WaterShallow" from (111, 18) to (117, 18)
    And Nelim's Pickle Tools: I lay the floor "WaterDeep" from (113, 18) to (115, 18)
    And Nelim's Pickle Tools: the area from (107, 19) to (119, 19) is cleared
    And Nelim's Pickle Tools: I lay the floor "MossyTerrain" from (104, 19) to (124, 19)
    And Nelim's Pickle Tools: I lay the floor "Gravel" from (109, 19) to (117, 19)
    And Nelim's Pickle Tools: I lay the floor "WaterShallow" from (110, 19) to (116, 19)
    And Nelim's Pickle Tools: I lay the floor "WaterDeep" from (111, 19) to (115, 19)
    And Nelim's Pickle Tools: the area from (106, 20) to (118, 20) is cleared
    And Nelim's Pickle Tools: I lay the floor "MossyTerrain" from (104, 20) to (124, 20)
    And Nelim's Pickle Tools: I lay the floor "Gravel" from (108, 20) to (116, 20)
    And Nelim's Pickle Tools: I lay the floor "WaterShallow" from (109, 20) to (115, 20)
    And Nelim's Pickle Tools: I lay the floor "WaterDeep" from (110, 20) to (114, 20)
    And Nelim's Pickle Tools: the area from (105, 21) to (117, 21) is cleared
    And Nelim's Pickle Tools: I lay the floor "MossyTerrain" from (104, 21) to (124, 21)
    And Nelim's Pickle Tools: I lay the floor "Gravel" from (107, 21) to (115, 21)
    And Nelim's Pickle Tools: I lay the floor "WaterShallow" from (108, 21) to (114, 21)
    And Nelim's Pickle Tools: I lay the floor "WaterDeep" from (109, 21) to (113, 21)
    And I spawn a "Plant_Reeds" at (108, 21)
    And I spawn a "Plant_Reeds" at (114, 21)
    And Nelim's Pickle Tools: the area from (104, 22) to (118, 22) is cleared
    And Nelim's Pickle Tools: I lay the floor "MossyTerrain" from (104, 22) to (124, 22)
    And Nelim's Pickle Tools: I lay the floor "Gravel" from (106, 22) to (116, 22)
    And Nelim's Pickle Tools: I lay the floor "WaterShallow" from (107, 22) to (115, 22)
    And Nelim's Pickle Tools: I lay the floor "WaterDeep" from (109, 22) to (113, 22)
    And Nelim's Pickle Tools: the area from (103, 23) to (117, 23) is cleared
    And Nelim's Pickle Tools: I lay the floor "MossyTerrain" from (104, 23) to (124, 23)
    And Nelim's Pickle Tools: I lay the floor "Gravel" from (105, 23) to (115, 23)
    And Nelim's Pickle Tools: I lay the floor "WaterShallow" from (106, 23) to (114, 23)
    And Nelim's Pickle Tools: I lay the floor "WaterDeep" from (108, 23) to (112, 23)
    And Nelim's Pickle Tools: the area from (103, 24) to (117, 24) is cleared
    And Nelim's Pickle Tools: I lay the floor "MossyTerrain" from (104, 24) to (124, 24)
    And Nelim's Pickle Tools: I lay the floor "Gravel" from (105, 24) to (115, 24)
    And Nelim's Pickle Tools: I lay the floor "WaterShallow" from (106, 24) to (114, 24)
    And Nelim's Pickle Tools: I lay the floor "WaterDeep" from (108, 24) to (112, 24)
    And Nelim's Pickle Tools: the area from (105, 25) to (117, 25) is cleared
    And Nelim's Pickle Tools: I lay the floor "MossyTerrain" from (104, 25) to (124, 25)
    And Nelim's Pickle Tools: I lay the floor "Gravel" from (107, 25) to (115, 25)
    And Nelim's Pickle Tools: I lay the floor "WaterShallow" from (108, 25) to (114, 25)
    And Nelim's Pickle Tools: I lay the floor "WaterDeep" from (109, 25) to (113, 25)
    And I spawn a "Plant_Reeds" at (108, 25)
    And I spawn a "Plant_Reeds" at (114, 25)
    And Nelim's Pickle Tools: the area from (106, 26) to (118, 26) is cleared
    And Nelim's Pickle Tools: I lay the floor "MossyTerrain" from (104, 26) to (124, 26)
    And Nelim's Pickle Tools: I lay the floor "Gravel" from (108, 26) to (116, 26)
    And Nelim's Pickle Tools: I lay the floor "WaterShallow" from (109, 26) to (115, 26)
    And Nelim's Pickle Tools: I lay the floor "WaterDeep" from (110, 26) to (114, 26)
    And Nelim's Pickle Tools: the area from (106, 27) to (118, 27) is cleared
    And Nelim's Pickle Tools: I lay the floor "MossyTerrain" from (104, 27) to (124, 27)
    And Nelim's Pickle Tools: I lay the floor "Gravel" from (108, 27) to (116, 27)
    And Nelim's Pickle Tools: I lay the floor "WaterShallow" from (109, 27) to (115, 27)
    And Nelim's Pickle Tools: I lay the floor "WaterDeep" from (110, 27) to (114, 27)
    And Nelim's Pickle Tools: the area from (107, 28) to (119, 28) is cleared
    And Nelim's Pickle Tools: I lay the floor "MossyTerrain" from (104, 28) to (124, 28)
    And Nelim's Pickle Tools: I lay the floor "Gravel" from (109, 28) to (117, 28)
    And Nelim's Pickle Tools: I lay the floor "WaterShallow" from (110, 28) to (116, 28)
    And Nelim's Pickle Tools: I lay the floor "WaterDeep" from (111, 28) to (115, 28)
    And Nelim's Pickle Tools: the area from (108, 29) to (120, 29) is cleared
    And Nelim's Pickle Tools: I lay the floor "MossyTerrain" from (104, 29) to (124, 29)
    And Nelim's Pickle Tools: I lay the floor "Gravel" from (110, 29) to (118, 29)
    And Nelim's Pickle Tools: I lay the floor "WaterShallow" from (111, 29) to (117, 29)
    And Nelim's Pickle Tools: I lay the floor "WaterDeep" from (112, 29) to (116, 29)
    And I spawn a "Plant_Reeds" at (111, 29)
    And I spawn a "Plant_Reeds" at (117, 29)
    And Nelim's Pickle Tools: the area from (108, 30) to (120, 30) is cleared
    And Nelim's Pickle Tools: I lay the floor "MossyTerrain" from (104, 30) to (124, 30)
    And Nelim's Pickle Tools: I lay the floor "Gravel" from (110, 30) to (118, 30)
    And Nelim's Pickle Tools: I lay the floor "WaterShallow" from (111, 30) to (117, 30)
    And Nelim's Pickle Tools: I lay the floor "WaterDeep" from (112, 30) to (116, 30)
    And Nelim's Pickle Tools: the area from (109, 31) to (121, 31) is cleared
    And Nelim's Pickle Tools: I lay the floor "MossyTerrain" from (104, 31) to (124, 31)
    And Nelim's Pickle Tools: I lay the floor "Gravel" from (111, 31) to (119, 31)
    And Nelim's Pickle Tools: I lay the floor "WaterShallow" from (112, 31) to (118, 31)
    And Nelim's Pickle Tools: I lay the floor "WaterDeep" from (113, 31) to (117, 31)
    And Nelim's Pickle Tools: the area from (109, 32) to (121, 32) is cleared
    And Nelim's Pickle Tools: I lay the floor "MossyTerrain" from (104, 32) to (124, 32)
    And Nelim's Pickle Tools: I lay the floor "Gravel" from (111, 32) to (119, 32)
    And Nelim's Pickle Tools: I lay the floor "WaterShallow" from (112, 32) to (118, 32)
    And Nelim's Pickle Tools: I lay the floor "WaterDeep" from (113, 32) to (117, 32)
    And Nelim's Pickle Tools: the area from (108, 33) to (122, 33) is cleared
    And Nelim's Pickle Tools: I lay the floor "MossyTerrain" from (104, 33) to (124, 33)
    And Nelim's Pickle Tools: I lay the floor "Gravel" from (110, 33) to (120, 33)
    And Nelim's Pickle Tools: I lay the floor "WaterShallow" from (111, 33) to (119, 33)
    And Nelim's Pickle Tools: I lay the floor "WaterDeep" from (113, 33) to (117, 33)
    And I spawn a "Plant_Reeds" at (111, 33)
    And I spawn a "Plant_Reeds" at (119, 33)
    And Nelim's Pickle Tools: the area from (108, 34) to (122, 34) is cleared
    And Nelim's Pickle Tools: I lay the floor "MossyTerrain" from (104, 34) to (124, 34)
    And Nelim's Pickle Tools: I lay the floor "Gravel" from (110, 34) to (120, 34)
    And Nelim's Pickle Tools: I lay the floor "WaterShallow" from (111, 34) to (119, 34)
    And Nelim's Pickle Tools: I lay the floor "WaterDeep" from (114, 34) to (116, 34)
    And Nelim's Pickle Tools: the area from (108, 35) to (122, 35) is cleared
    And Nelim's Pickle Tools: I lay the floor "MossyTerrain" from (104, 35) to (124, 35)
    And Nelim's Pickle Tools: I lay the floor "Gravel" from (110, 35) to (120, 35)
    And Nelim's Pickle Tools: I lay the floor "WaterShallow" from (111, 35) to (119, 35)
    And Nelim's Pickle Tools: I lay the floor "WaterDeep" from (114, 35) to (116, 35)
    And Nelim's Pickle Tools: the area from (109, 36) to (121, 36) is cleared
    And Nelim's Pickle Tools: I lay the floor "MossyTerrain" from (104, 36) to (124, 36)
    And Nelim's Pickle Tools: I lay the floor "Gravel" from (111, 36) to (119, 36)
    And Nelim's Pickle Tools: I lay the floor "WaterShallow" from (112, 36) to (118, 36)
    And Nelim's Pickle Tools: I lay the floor "WaterDeep" from (113, 36) to (117, 36)
    And Nelim's Pickle Tools: the area from (109, 37) to (121, 37) is cleared
    And Nelim's Pickle Tools: I lay the floor "MossyTerrain" from (104, 37) to (124, 37)
    And Nelim's Pickle Tools: I lay the floor "Gravel" from (111, 37) to (119, 37)
    And Nelim's Pickle Tools: I lay the floor "WaterShallow" from (112, 37) to (118, 37)
    And Nelim's Pickle Tools: I lay the floor "WaterDeep" from (113, 37) to (117, 37)
    And I spawn a "Plant_Reeds" at (112, 37)
    And I spawn a "Plant_Reeds" at (118, 37)
    And Nelim's Pickle Tools: the area from (109, 38) to (121, 38) is cleared
    And Nelim's Pickle Tools: I lay the floor "MossyTerrain" from (104, 38) to (124, 38)
    And Nelim's Pickle Tools: I lay the floor "Gravel" from (111, 38) to (119, 38)
    And Nelim's Pickle Tools: I lay the floor "WaterShallow" from (112, 38) to (118, 38)
    And Nelim's Pickle Tools: I lay the floor "WaterDeep" from (113, 38) to (117, 38)
    And Nelim's Pickle Tools: the area from (109, 39) to (121, 39) is cleared
    And Nelim's Pickle Tools: I lay the floor "MossyTerrain" from (104, 39) to (124, 39)
    And Nelim's Pickle Tools: I lay the floor "Gravel" from (111, 39) to (119, 39)
    And Nelim's Pickle Tools: I lay the floor "WaterShallow" from (112, 39) to (118, 39)
    And Nelim's Pickle Tools: I lay the floor "WaterDeep" from (113, 39) to (117, 39)
    And Nelim's Pickle Tools: the area from (109, 40) to (121, 40) is cleared
    And Nelim's Pickle Tools: I lay the floor "MossyTerrain" from (104, 40) to (124, 40)
    And Nelim's Pickle Tools: I lay the floor "Gravel" from (111, 40) to (119, 40)
    And Nelim's Pickle Tools: I lay the floor "WaterShallow" from (112, 40) to (118, 40)
    And Nelim's Pickle Tools: I lay the floor "WaterDeep" from (113, 40) to (117, 40)
    And Nelim's Pickle Tools: the area from (109, 41) to (121, 41) is cleared
    And Nelim's Pickle Tools: I lay the floor "MossyTerrain" from (104, 41) to (124, 41)
    And Nelim's Pickle Tools: I lay the floor "Gravel" from (111, 41) to (119, 41)
    And Nelim's Pickle Tools: I lay the floor "WaterShallow" from (112, 41) to (118, 41)
    And Nelim's Pickle Tools: I lay the floor "WaterDeep" from (113, 41) to (117, 41)
    And I spawn a "Plant_Reeds" at (112, 41)
    And I spawn a "Plant_Reeds" at (118, 41)
    And Nelim's Pickle Tools: the area from (109, 42) to (121, 42) is cleared
    And Nelim's Pickle Tools: I lay the floor "MossyTerrain" from (104, 42) to (124, 42)
    And Nelim's Pickle Tools: I lay the floor "Gravel" from (111, 42) to (119, 42)
    And Nelim's Pickle Tools: I lay the floor "WaterShallow" from (112, 42) to (118, 42)
    And Nelim's Pickle Tools: I lay the floor "WaterDeep" from (113, 42) to (117, 42)
    And Nelim's Pickle Tools: the area from (109, 43) to (121, 43) is cleared
    And Nelim's Pickle Tools: I lay the floor "MossyTerrain" from (104, 43) to (124, 43)
    And Nelim's Pickle Tools: I lay the floor "Gravel" from (111, 43) to (119, 43)
    And Nelim's Pickle Tools: I lay the floor "WaterShallow" from (112, 43) to (118, 43)
    And Nelim's Pickle Tools: I lay the floor "WaterDeep" from (113, 43) to (117, 43)
    And Nelim's Pickle Tools: the area from (108, 44) to (122, 44) is cleared
    And Nelim's Pickle Tools: I lay the floor "MossyTerrain" from (104, 44) to (124, 44)
    And Nelim's Pickle Tools: I lay the floor "Gravel" from (110, 44) to (120, 44)
    And Nelim's Pickle Tools: I lay the floor "WaterShallow" from (111, 44) to (119, 44)
    And Nelim's Pickle Tools: I lay the floor "WaterDeep" from (113, 44) to (117, 44)
    And Nelim's Pickle Tools: the area from (107, 45) to (123, 45) is cleared
    And Nelim's Pickle Tools: I lay the floor "MossyTerrain" from (104, 45) to (124, 45)
    And Nelim's Pickle Tools: I lay the floor "Gravel" from (109, 45) to (121, 45)
    And Nelim's Pickle Tools: I lay the floor "WaterShallow" from (110, 45) to (120, 45)
    And Nelim's Pickle Tools: I lay the floor "WaterDeep" from (112, 45) to (118, 45)
    And I spawn a "Plant_Reeds" at (110, 45)
    And I spawn a "Plant_Reeds" at (120, 45)
    And Nelim's Pickle Tools: the area from (106, 46) to (122, 46) is cleared
    And Nelim's Pickle Tools: I lay the floor "MossyTerrain" from (104, 46) to (124, 46)
    And Nelim's Pickle Tools: I lay the floor "Gravel" from (108, 46) to (120, 46)
    And Nelim's Pickle Tools: I lay the floor "WaterShallow" from (109, 46) to (119, 46)
    And Nelim's Pickle Tools: I lay the floor "WaterDeep" from (111, 46) to (117, 46)
    And Nelim's Pickle Tools: the area from (107, 47) to (121, 47) is cleared
    And Nelim's Pickle Tools: I lay the floor "MossyTerrain" from (104, 47) to (124, 47)
    And Nelim's Pickle Tools: I lay the floor "Gravel" from (109, 47) to (119, 47)
    And Nelim's Pickle Tools: I lay the floor "WaterShallow" from (110, 47) to (118, 47)
    And Nelim's Pickle Tools: I lay the floor "WaterDeep" from (111, 47) to (117, 47)
    And Nelim's Pickle Tools: the area from (107, 48) to (121, 48) is cleared
    And Nelim's Pickle Tools: I lay the floor "MossyTerrain" from (104, 48) to (124, 48)
    And Nelim's Pickle Tools: I lay the floor "Gravel" from (109, 48) to (119, 48)
    And Nelim's Pickle Tools: I lay the floor "WaterShallow" from (110, 48) to (118, 48)
    And Nelim's Pickle Tools: I lay the floor "WaterDeep" from (111, 48) to (117, 48)
    And Nelim's Pickle Tools: the area from (106, 49) to (120, 49) is cleared
    And Nelim's Pickle Tools: I lay the floor "MossyTerrain" from (104, 49) to (124, 49)
    And Nelim's Pickle Tools: I lay the floor "Gravel" from (108, 49) to (118, 49)
    And Nelim's Pickle Tools: I lay the floor "WaterShallow" from (109, 49) to (117, 49)
    And Nelim's Pickle Tools: I lay the floor "WaterDeep" from (110, 49) to (116, 49)
    And I spawn a "Plant_Reeds" at (109, 49)
    And I spawn a "Plant_Reeds" at (117, 49)
    And Nelim's Pickle Tools: the area from (106, 50) to (120, 50) is cleared
    And Nelim's Pickle Tools: I lay the floor "MossyTerrain" from (104, 50) to (124, 50)
    And Nelim's Pickle Tools: I lay the floor "Gravel" from (108, 50) to (118, 50)
    And Nelim's Pickle Tools: I lay the floor "WaterShallow" from (109, 50) to (117, 50)
    And Nelim's Pickle Tools: I lay the floor "WaterDeep" from (110, 50) to (116, 50)
    And Nelim's Pickle Tools: the area from (106, 51) to (120, 51) is cleared
    And Nelim's Pickle Tools: I lay the floor "MossyTerrain" from (104, 51) to (124, 51)
    And Nelim's Pickle Tools: I lay the floor "Gravel" from (108, 51) to (118, 51)
    And Nelim's Pickle Tools: I lay the floor "WaterShallow" from (109, 51) to (117, 51)
    And Nelim's Pickle Tools: I lay the floor "WaterDeep" from (111, 51) to (115, 51)
    And Nelim's Pickle Tools: the area from (106, 52) to (120, 52) is cleared
    And Nelim's Pickle Tools: I lay the floor "MossyTerrain" from (104, 52) to (124, 52)
    And Nelim's Pickle Tools: I lay the floor "Gravel" from (108, 52) to (118, 52)
    And Nelim's Pickle Tools: I lay the floor "WaterShallow" from (109, 52) to (117, 52)
    And Nelim's Pickle Tools: I lay the floor "WaterDeep" from (111, 52) to (115, 52)
    And Nelim's Pickle Tools: the area from (107, 53) to (121, 53) is cleared
    And Nelim's Pickle Tools: I lay the floor "MossyTerrain" from (104, 53) to (124, 53)
    And Nelim's Pickle Tools: I lay the floor "Gravel" from (109, 53) to (119, 53)
    And Nelim's Pickle Tools: I lay the floor "WaterShallow" from (110, 53) to (118, 53)
    And Nelim's Pickle Tools: I lay the floor "WaterDeep" from (111, 53) to (117, 53)
    And I spawn a "Plant_Reeds" at (110, 53)
    And I spawn a "Plant_Reeds" at (118, 53)
    And Nelim's Pickle Tools: the area from (107, 54) to (121, 54) is cleared
    And Nelim's Pickle Tools: I lay the floor "MossyTerrain" from (104, 54) to (124, 54)
    And Nelim's Pickle Tools: I lay the floor "Gravel" from (109, 54) to (119, 54)
    And Nelim's Pickle Tools: I lay the floor "WaterShallow" from (110, 54) to (118, 54)
    And Nelim's Pickle Tools: I lay the floor "WaterDeep" from (111, 54) to (117, 54)
    And Nelim's Pickle Tools: the area from (106, 55) to (122, 55) is cleared
    And Nelim's Pickle Tools: I lay the floor "MossyTerrain" from (104, 55) to (124, 55)
    And Nelim's Pickle Tools: I lay the floor "Gravel" from (108, 55) to (120, 55)
    And Nelim's Pickle Tools: I lay the floor "WaterShallow" from (109, 55) to (119, 55)
    And Nelim's Pickle Tools: I lay the floor "WaterDeep" from (111, 55) to (117, 55)
    And Nelim's Pickle Tools: the area from (106, 56) to (122, 56) is cleared
    And Nelim's Pickle Tools: I lay the floor "MossyTerrain" from (104, 56) to (124, 56)
    And Nelim's Pickle Tools: I lay the floor "Gravel" from (108, 56) to (120, 56)
    And Nelim's Pickle Tools: I lay the floor "WaterShallow" from (109, 56) to (119, 56)
    And Nelim's Pickle Tools: I lay the floor "WaterDeep" from (111, 56) to (117, 56)
    And Nelim's Pickle Tools: the area from (106, 57) to (122, 57) is cleared
    And Nelim's Pickle Tools: I lay the floor "MossyTerrain" from (104, 57) to (124, 57)
    And Nelim's Pickle Tools: I lay the floor "Gravel" from (108, 57) to (120, 57)
    And Nelim's Pickle Tools: I lay the floor "WaterShallow" from (109, 57) to (119, 57)
    And Nelim's Pickle Tools: I lay the floor "WaterDeep" from (111, 57) to (117, 57)
    And Nelim's Pickle Tools: the area from (107, 58) to (121, 58) is cleared
    And Nelim's Pickle Tools: I lay the floor "MossyTerrain" from (104, 58) to (124, 58)
    And Nelim's Pickle Tools: I lay the floor "Gravel" from (109, 58) to (119, 58)
    And Nelim's Pickle Tools: I lay the floor "WaterShallow" from (110, 58) to (118, 58)
    And Nelim's Pickle Tools: I lay the floor "WaterDeep" from (111, 58) to (117, 58)
    And Nelim's Pickle Tools: the area from (107, 59) to (121, 59) is cleared
    And Nelim's Pickle Tools: I lay the floor "MossyTerrain" from (104, 59) to (124, 59)
    And Nelim's Pickle Tools: I lay the floor "Gravel" from (109, 59) to (119, 59)
    And Nelim's Pickle Tools: I lay the floor "WaterShallow" from (110, 59) to (118, 59)
    And Nelim's Pickle Tools: I lay the floor "WaterDeep" from (111, 59) to (117, 59)
    And Nelim's Pickle Tools: the area from (107, 60) to (121, 60) is cleared
    And Nelim's Pickle Tools: I lay the floor "MossyTerrain" from (104, 60) to (124, 60)
    And Nelim's Pickle Tools: I lay the floor "Gravel" from (109, 60) to (119, 60)
    And Nelim's Pickle Tools: I lay the floor "WaterShallow" from (110, 60) to (118, 60)
    And Nelim's Pickle Tools: I lay the floor "WaterDeep" from (111, 60) to (117, 60)
    When Nelim's Pickle Tools: I frame the cell (114, 30) at zoom 20
    And I take a screenshot "river-upstream-middle"
    And Nelim's Pickle Tools: I frame the cell (114, 10) at zoom 14
    And I take a screenshot "river-upstream-edge"
    And Nelim's Pickle Tools: I frame the cell (114, 52) at zoom 16
    And I take a screenshot "river-upstream-join"
    And I save and reload as "nelims-tribe-river"
