<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <AssemblyName>Nelim.PickleTools.ScreenshotStudio</AssemblyName>
    <OutputPath>../Mod/Pickle/Assemblies/</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <DebugType>none</DebugType>
    <Deterministic>true</Deterministic>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Krafs.Rimworld.Ref" Version="1.6.4871" ExcludeAssets="runtime" PrivateAssets="all" />
    <PackageReference Include="RimWorks.Pickle.Ref" Version="4.8.3" ExcludeAssets="runtime" PrivateAssets="all" />
  </ItemGroup>
</Project>
